export default class APIMethod {
    static register = 'register'
    static login = 'login'
    static logout = 'logout'
    static subscribe = 'subscribe'
    static unsubscribe = 'unsubscribe'
    static fetchQuadrant = 'fetchQuadrant'
    static getQuadrantSize = 'getQuadrantSize'
    static getCoordMinMax = 'getCoordMinMax'
    static getFontSizeMinMax = 'getFontSizeMinMax'
    static getAgeLimit = 'getAgeLimit'
    static setView = 'setView'
    static setFontsize = 'setFontsize'
    static setFeed = 'setFeed'
    static setBlink = 'setBlink'
    static read = 'read'
    static move = 'move'
    static goto = 'goto'
    static type = 'type'
    static space = 'space'
    static backspace = 'backspace'
    static crlf = 'crlf'
    static cr = 'cr'
}